create table if not exists public.contact_form_submissions (
  id bigint generated by default as identity primary key,
  email text not null,
  website_type text not null,
  created_at timestamptz not null default now()
);

create index if not exists contact_form_submissions_created_at_idx
  on public.contact_form_submissions (created_at desc);

alter table public.contact_form_submissions enable row level security;

drop policy if exists "contact_form_submissions_insert_public" on public.contact_form_submissions;
create policy "contact_form_submissions_insert_public"
  on public.contact_form_submissions
  for insert
  to anon, authenticated
  with check (true);
